#
# Copyright (C) 2018 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/mt8512
ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/include/

obj-y += mt8512-cpufreq.o
obj-y += mtk_cpufreq_api.o
obj-y += mtk_static_power.o
obj-y += mtk_power_throttle.o
obj-y += mtk_dcm.o
obj-y += mtk_svs.o
obj-y += mtk_hotplug_thermal.o
ifeq ($(CONFIG_ARCH_MTK_PROJECT), "aud8113tp1")
obj-y += mt8113_sloa_fs.o
else ifeq ($(CONFIG_ARCH_MTK_PROJECT), "aud8113lp1")
obj-y += mt8113_sloa_fs.o
else
obj-y += mt8512_sloa_fs.o
obj-y += mtk_power_solution.o
endif
