#include "../cfgdefault/CFG_Custom1_Default.h"
#include "../cfgdefault/CFG_GPS_Default.h"
#include "../cfgdefault/CFG_PRODUCT_INFO_Default.h"
#include "../cfgdefault/CFG_WIFI_Default.h"
#include "../cfgdefault/CFG_XoCap_Default.h"
#include "../cfgdefault/CFG_Ethernet_File.h"
