PREFIX = ../install
CROSS = arm-linux-
CROSS_COMPILER = $(CROSS:%-=%)
ROOT = ../install/$(CROSS_COMPILER)
DEP_LIBS =
CODEBASE=DEFAULT
INCLUDE_ADD = -Ilibnvram -Ilibfile_op -I$(ROOT)/include/custom/$(PRJ_FILENAME)/cgen/cfgfileinc -I$(ROOT)/include/custom/$(PRJ_FILENAME)/cgen/cfgdefault -I$(ROOT)/include/custom/$(PRJ_FILENAME)/cgen/inc -I$(ROOT)/include/custom/$(PRJ_FILENAME)/cgen -I$(ROOT)/include/custom/$(CODEBASE)/cgen/cfgfileinc -I$(ROOT)/include/custom/$(CODEBASE)/cgen/cfgfileinc -I$(ROOT)/include/custom/$(CODEBASE)/cgen/cfgdefault -I$(ROOT)/include/custom/$(CODEBASE)/cgen/inc -I$(ROOT)/include/custom/$(CODEBASE)/cgen
LDFLAGS_ADD =
INSTALL = install
CLEAN = clean
MIN = 1
NAME =
ifeq ($(strip $(CROSS)), arm-linux-)
    OFLAGS = -O2 $(THUMB)
else
    OFLAGS = -O2
endif
CFLAGS = -g $(DEF_CFLAGS) $(OFLAGS)

LIB =
VPATH = $(NAME)
LOBJ = $(patsubst %.S,%.o, \
       $(patsubst %.s,%.o, \
       $(patsubst %.c,%.o, \
       $(patsubst %.cpp, %.o, \
       $(notdir $(foreach DIR,$(VPATH),\
       $(wildcard $(DIR)/*.S)  \
       $(wildcard $(DIR)/*.s)  \
       $(wildcard $(DIR)/*.c)  \
       $(wildcard $(DIR)/*.cpp)))))))


include bin/Makefile.config
#include bin/Makefile.template

APDB:
	export LD_LIBRARY_PATH=./apdb && \
	gcc -E $(INCLUDE_ADD) apdb/apeditor/app_parse_db.c > app_temp_db && \
	apdb/Cgen -c app_temp_db apdb/cgencfg/tgt_cnf apdb/cgencfg/pc_cnf APDB2 APDB_ENUM && \
	apdb/Cgen -cm APDB APDB2 app_temp_db APDB_ENUM

install: APDB
	mkdir -p $(ROOT)/out
	cp -af APDB $(ROOT)/out/APDB

clean:
	rm -f APDB APDB2 APDB_ENUM app_temp_db
