#
# Copyright (C) 2019 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

# drivers/video/mt8512/Makefile
#

obj-$(CONFIG_MTK_FB) += mtk_dpi_fb.o 	\
			mtk_dpi_panel.o \
			mtkfb.o		\
			ddp_path.o	\
			ddp_rdma.o

subdir-ccflags-y += -Werror

subdir-ccflags-y += -DMT8512_DISP_SUPPORT

