/* Copyright Statement:
*
* This software/firmware and related documentation ("MediaTek Software") are
* protected under relevant copyright laws. The information contained herein
* is confidential and proprietary to MediaTek Inc. and/or its licensors.
* Without the prior written permission of MediaTek inc. and/or its licensors,
* any reproduction, modification, use or disclosure of MediaTek Software,
* and information contained herein, in whole or in part, shall be strictly prohibited.
*/
/* MediaTek Inc. (C) 2015. All rights reserved.
*
* BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
* THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
* RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
* AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
* NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
* SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
* SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
* THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
* THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
* CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
* SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
* STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
* CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
* AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
* OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
* MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
* The following software/firmware and/or related documentation ("MediaTek Software")
* have been modified by MediaTek Inc. All revisions are subject to any receiver\'s
* applicable license agreements with MediaTek Inc.
*/

#ifndef _MT_PTP_
#define _MT_PTP_

#include "platform/pmic_wrap.h"
#include "platform/pll.h"

extern u32 get_devinfo_with_index(u32 index);

/* PTP Register Definition */
#define PTP_BASEADDR		(IO_PHYS + 0x0100D000)
#define PTP_REVISIONID		(PTP_BASEADDR + 0x0FC)
#define PTP_DESCHAR		(PTP_BASEADDR + 0x200)
#define PTP_TEMPCHAR		(PTP_BASEADDR + 0x204)
#define PTP_DETCHAR		(PTP_BASEADDR + 0x208)
#define PTP_AGECHAR		(PTP_BASEADDR + 0x20C)
#define PTP_DCCONFIG		(PTP_BASEADDR + 0x210)
#define PTP_AGECONFIG		(PTP_BASEADDR + 0x214)
#define PTP_FREQPCT30		(PTP_BASEADDR + 0x218)
#define PTP_FREQPCT74		(PTP_BASEADDR + 0x21C)
#define PTP_LIMITVALS		(PTP_BASEADDR + 0x220)
#define PTP_VBOOT		(PTP_BASEADDR + 0x224)
#define PTP_DETWINDOW		(PTP_BASEADDR + 0x228)
#define PTP_PTPCONFIG		(PTP_BASEADDR + 0x22C)
#define PTP_TSCALCS		(PTP_BASEADDR + 0x230)
#define PTP_RUNCONFIG		(PTP_BASEADDR + 0x234)
#define PTP_PTPEN		(PTP_BASEADDR + 0x238)
#define PTP_INIT2VALS		(PTP_BASEADDR + 0x23C)
#define PTP_DCVALUES		(PTP_BASEADDR + 0x240)
#define PTP_AGEVALUES		(PTP_BASEADDR + 0x244)
#define PTP_VOP30		(PTP_BASEADDR + 0x248)
#define PTP_VOP74		(PTP_BASEADDR + 0x24C)
#define PTP_TEMP		(PTP_BASEADDR + 0x250)
#define PTP_PTPINTSTS		(PTP_BASEADDR + 0x254)
#define PTP_PTPINTSTSRAW	(PTP_BASEADDR + 0x258)
#define PTP_PTPINTEN		(PTP_BASEADDR + 0x25C)
#define PTP_PTPCHKSHIFT		(PTP_BASEADDR + 0x264)
#define PTP_VDESIGN30		(PTP_BASEADDR + 0x26C)
#define PTP_VDESIGN74		(PTP_BASEADDR + 0x270)
#define PTP_DVT30		(PTP_BASEADDR + 0x274)
#define PTP_DVT74		(PTP_BASEADDR + 0x278)
#define PTP_AGECOUNT		(PTP_BASEADDR + 0x27C)
#define PTP_SMSTATE0		(PTP_BASEADDR + 0x280)
#define PTP_SMSTATE1		(PTP_BASEADDR + 0x284)
#define PTP_PTPCTL0		(PTP_BASEADDR + 0x288)
#define PTP_PTPCORESEL		(PTP_BASEADDR + 0x400)
/* #define SYSTEMCLK_CG_EN		31:31
 * #define PTPODCORE1EN		17:17
 * #define PTPODCORE0EN		16:16
 */
/* #define APBSEL		3:0 write this in mt_ptp.c */

#define PTP_THERMINTST		(PTP_BASEADDR + 0x404)
#define PTP_PTPODINTST		(PTP_BASEADDR + 0x408)
/* #define PTPODINT0		0:0 not used anymore */
/* #define PTPODINT1		1:1 not used anymore */
/* #define PTPODINT2		2:2 not used anymore */
/* #define PTPODINT3		3:3 not used anymore */

#define PTP_THSTAGE0ST		(PTP_BASEADDR + 0x40C)
#define PTP_THSTAGE1ST		(PTP_BASEADDR + 0x410)
#define PTP_THSTAGE2ST		(PTP_BASEADDR + 0x414)
#define PTP_THAHBST0		(PTP_BASEADDR + 0x418)
#define PTP_THAHBST1		(PTP_BASEADDR + 0x41C)
#define PTP_PTPSPARE0		(PTP_BASEADDR + 0x420)
#define PTP_PTPSPARE1		(PTP_BASEADDR + 0x424)
#define PTP_PTPSPARE2		(PTP_BASEADDR + 0x428)
#define PTP_PTPSPARE3		(PTP_BASEADDR + 0x42C)
#define PTP_THSLPEVEB		(PTP_BASEADDR + 0x430)

/* PTP Extern Function */
extern void ptp_init(void);

#endif
